version: '3.8'

services:
  # Main Application Database
  db:
    image: postgres:latest
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: travel_recommendation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 5s

  # Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"
      - "6334:6334"

volumes:
  pg_data:
  qdrant_data:
