name: Lint, Format, and Test

on:
  push:
    branches: [main, alembic]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: travel_recommendation
        options: >-
          --health-cmd "pg_isready -U postgres" \
          --health-interval 10s \
          --health-timeout 5s \
          --health-retries 5
    env:
      DATABASE_URL: postgresql+asyncpg://postgres:password@localhost:5432/travel_recommendation
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black pytest

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -U postgres; do
            echo "Waiting for postgres..."
            sleep 2
          done

      - name: Check formatting with black
        run: |
          black . --check --exclude 'alembic/versions/69d0b2be3d24_refactored_initial_migration.py'

      - name: Lint with flake8
        run: |
          flake8 . --exclude=venv,.git,__pycache__ --max-line-length=100

      - name: Run tests
        run: |
          pytest
